# Generated by Django 5.2.4 on 2025-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('is_new', models.BooleanField(default=False, help_text="Check if 'NEW' badge dikhana hai")),
                ('features', models.JSONField(default=list, help_text="Example: ['3 Months Live Training', '5+ Real Projects', 'Job Assistance']")),
                ('order', models.PositiveIntegerField(default=0, help_text='Chhota number = pehle dikhega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
