# Generated by Django 5.2.4 on 2025-11-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('studentId', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('Full Stack Web Development', 'Full Stack Web Development'), ('Python & Data Science', 'Python & Data Science'), ('Digital Marketing Mastery', 'Digital Marketing Mastery')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-created_at'],
            },
        ),
    ]
