# Generated by Django 5.2.4 on 2026-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='features',
            field=models.JSONField(default=list, help_text='Example: ["3 Months Live Training", "5+ Real Projects", "Job Assistance"]'),
        ),
    ]
