# Generated by Django 5.2.4 on 2026-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_course_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
