# Generated by Django 5.2.4 on 2026-03-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_course_options_course_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_display',
            field=models.CharField(blank=True, default='', help_text="Display text for course duration, e.g. '4m - 6m', '3 Months Live'", max_length=50),
        ),
    ]
