# Generated by Django 5.2.4 on 2026-03-09 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Client_student', '0016_alter_student_dob'),
        ('mainApp', '0007_course_duration_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('message', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(upload_to='payments/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_Client_student.student')),
            ],
        ),
    ]
