# Generated by Django 5.2.4 on 2026-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterField(
            model_name='course',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Discounted price if there's an offer", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_display',
            field=models.CharField(blank=True, default='', help_text='Display text for course duration', max_length=50),
        ),
    ]
