# Generated by Django 5.2.4 on 2026-04-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_testimonial_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
