# Generated by Django 5.2.4 on 2026-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
