# Generated by Django 5.2.4 on 2026-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_testimonial_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
