# Generated by Django 5.2.4 on 2026-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_testimonial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='isaccepted',
            field=models.BooleanField(default=False),
        ),
    ]
