# Generated by Django 5.2.4 on 2026-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_testimonial_isaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_employee_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_student_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='client_uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
