# Generated by Django 5.2.4 on 2025-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Client_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
