# Generated by Django 5.2.4 on 2025-11-29 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Client_student', '0003_alter_employee_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
