# Generated by Django 5.2.4 on 2026-03-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Client_student', '0011_timesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='uuid',
            new_name='emp_uuid',
        ),
    ]
