# Generated by Django 5.2.4 on 2026-03-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Client_student', '0012_rename_uuid_employee_emp_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='uuid',
            new_name='stu_uuid',
        ),
    ]
