# Generated by Django 5.2.4 on 2026-03-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Client_student', '0013_rename_uuid_student_stu_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='jointBy',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
