# Generated by Django 5.2.4 on 2026-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Client_student', '0014_remove_student_course_student_course_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', editable=False, max_length=50),
        ),
    ]
