# Generated by Django 5.2.4 on 2026-05-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Client_student', '0016_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('teacher', 'Teacher'), ('account-manager', 'Account Manager'), ('manager', 'Manager'), ('client', 'Client')], default='employee', max_length=50),
        ),
    ]
